include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SyslogViewerPrefs
SyslogViewerPrefs_FILES = SyslogViewerPrefs.m
SyslogViewerPrefs_FRAMEWORKS = UIKit Preferences
SyslogViewerPrefs_INSTALL_PATH = /var/jb/Library/PreferenceBundles
SyslogViewerPrefs_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/bundle.mk