include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SyslogViewerPrefs
SyslogViewerPrefs_FILES = SyslogViewerPrefs.m Root.plist
SyslogViewerPrefs_INSTALL_PATH = /Library/PreferenceBundles
SyslogViewerPrefs_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/bundle.mk
